### ISSUE TITLE
Please add failureFlash example

### ISSUE THREAD

**Issue by koutsenko** [passport/express-4.x-facebook-example#3]
I trying to use failureFlash and can't get it work.

`return done(null, false,  request.flash('auth', 'This email is already bound to another account'));    `

That works only with local strategy, not facebook strategy. failureFlash: true is passed to options.
Please add it to example or confirm that it is not supported.
Express 4.

Thanks.

**Comment by jaredhanson** [comment]
Could you please add it to the example and confirm that it works?  If so, close the issue

**Comment by koutsenko** [comment]
What I trying to say, is : this example don't use flash messages and I can't get it work.
Maybe it is a simple example, so there is no need to pass flash messages.

But what about complex situation "one profile - many ways to login", where I must check the presented Facebook credentials bound to another profile before linking it to current profile. It's situation when all is right from Facebook side, but from my side I possibly want reject auth attempt. I wrote complex working strategy, but can't deliver flash message to user.

It seems there is no sense to write this logic to this simple example.
What else can I do?
Using Express 4 and connect-flash module.

Thanks.

**Comment by koutsenko** [comment]
I'm sorry, i've figured it all out.
I've used custom callback as told here http://passportjs.org/docs , and processed all routes, problem was in the different flash variable names.

The PassportJS library works excellent.
