### ISSUE TITLE
OUTDATED readme

### ISSUE THREAD

**Issue by velociraptor111** [passport/express-4.x-facebook-example#31]
1. the command to run should be `FACEBOOK_CLIENT_ID=__FACEBOOK_CLIENT_ID__ FACEBOOK_CLIENT_SECRET=__FACEBOOK_CLIENT_SECRET__ node server.js` 

2. Default port should go to `8080` rather than `3000` as written in the Readme.md

**Comment by jaredhanson** [comment]
Fixed.
